name: Rebuild docs
on:
  push:
    branches:
      - master

jobs:
  rebuild:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'update version')"
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: sqlcollaborative/docs
          event-type: rebuild-pages
